spring:
  application:
    name: monew

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/monew}
    username: ${DB_USERNAME:monew_user}
    password: ${DB_PASSWORD:monew1234}

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    base-url: https://naverapihub.apigw.ntruss.com
